### ISSUE TITLE
Discrepancy between vocabulary size and the number of vectors for Glove.

### ISSUE THREAD

**Issue by jlowryduda** [kudkudak/word-embeddings-benchmarks#33]
I ran `evaluate_embeddings.py` script, when the following error occurred:

```
Extracting data from path/web_data/embeddings/glove.840B.300d/glove.840B.300d.zip...
   ...done.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "evaluate_embeddings.py", line 67, in run_job
    w = getattr(embeddings, fn)(**kwargs)
  File "path/to/embeddings-benchmarks/word-embeddings-benchmarks/web/embeddings.py", line 142, in fetch_GloVe
    load_kwargs={"vocab_size": vocab_size[corpus], "dim": dim})
  File "path/to/embeddings-benchmarks/word-embeddings-benchmarks/web/embeddings.py", line 41, in load_embedding
    w = Embedding.from_glove(fname, **load_kwargs)
  File "path/to/embeddings-benchmarks/word-embeddings-benchmarks/web/embedding.py", line 311, in from_glove
    return Embedding(vocabulary=OrderedVocabulary(words), vectors=vectors[0:len(words)])
  File "path/to/experiments/embeddings-benchmarks/word-embeddings-benchmarks/web/embedding.py", line 34, in __init__
    .format(len(vocabulary), self.vectors.shape[0]))
ValueError: Vocabulary has 2195895 items but we have 2196017 vectors.
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "evaluate_embeddings.py", line 72, in <module>
    Pool(opts.n_jobs).map(run_job, jobs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
ValueError: Vocabulary has 2195895 items but we have 2196017 vectors.
```
Any idea what might be happening there?

As a side not, I encountered  some encoding problems earlier while running the same script. It looks to me like the file that `load_embedding` is trying to load was pickled using Python2, while I'm running Python3. I solved it naively by passing latin1 encoding to `pickle.load()`, but could use a more robust solution.

```
06:02:43 INFO:Processing fetch_SG_GoogleNews_.csv
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "evaluate_embeddings.py", line 67, in run_job
    w = getattr(embeddings, fn)(**kwargs)
  File "path/to/embeddings-benchmarks/word-embeddings-benchmarks/web/embeddings.py", line 279, in fetch_NMT
    lower=lower, clean_words=clean_words)
  File "path/to/embeddings-benchmarks/word-embeddings-benchmarks/web/embeddings.py", line 43, in load_embedding
    d = pickle.load(open(fname, "rb"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 0: ordinal not in range(128)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "evaluate_embeddings.py", line 72, in <module>
    Pool(opts.n_jobs).map(run_job, jobs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 0: ordinal not in range(128)
Downloading data from https://www.dropbox.com/s/bnm0trligffakd9/GoogleNews-vectors-negative300.bin.gz ...
```

**Comment by kudkudak** [comment]
Thanks, we are looking into it :)

**Comment by kudkudak** [comment]
Should be fixed :)
