### ISSUE TITLE
SSL error in the "Calculating similarity benchmarks" phase

### ISSUE THREAD

**Issue by acrola** [kudkudak/word-embeddings-benchmarks#79]
I get the following log:

03:46:09 INFO:Calculating similarity benchmarks
Traceback (most recent call last):
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/evaluate_on_all.py", line 83, in <module>
    results = evaluate_on_all(w)
  File "/home/lior/.local/lib/python3.6/site-packages/web-0.0.1-py3.6.egg/web/evaluate.py", line 370, in evaluate_on_all
    "TR9856": fetch_TR9856(),
  File "/home/lior/.local/lib/python3.6/site-packages/web-0.0.1-py3.6.egg/web/datasets/similarity.py", line 335, in fetch_TR9856
    'similarity', uncompress=True, verbose=0),
  File "/home/lior/.local/lib/python3.6/site-packages/web-0.0.1-py3.6.egg/web/datasets/utils.py", line 741, in _fetch_file
    handlers=handlers)
  File "/home/lior/.local/lib/python3.6/site-packages/web-0.0.1-py3.6.egg/web/datasets/utils.py", line 648, in _fetch_helper
    data = url_opener.open(request)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/lior/anaconda3/envs/py36/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

**Comment by cristian-tamblay** [comment]
Getting the same error trying to run the script: 
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
Log:
07:42:41 INFO:Calculating similarity benchmarks

Dataset created in /home/ctamblay/web_data/similarity

Traceback (most recent call last):
  File "./scripts/evaluate_on_all.py", line 83, in <module>
    results = evaluate_on_all(w)
  File "/usr/local/lib/python2.7/dist-packages/web-0.0.1-py2.7.egg/web/evaluate.py", line 370, in evaluate_on_all
    "TR9856": fetch_TR9856(),
  File "/usr/local/lib/python2.7/dist-packages/web-0.0.1-py2.7.egg/web/datasets/similarity.py", line 335, in fetch_TR9856
    'similarity', uncompress=True, verbose=0),
  File "/usr/local/lib/python2.7/dist-packages/web-0.0.1-py2.7.egg/web/datasets/utils.py", line 741, in _fetch_file
    handlers=handlers)
  File "/usr/local/lib/python2.7/dist-packages/web-0.0.1-py2.7.egg/web/datasets/utils.py", line 648, in _fetch_helper
    data = url_opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

**Comment by cristian-tamblay** [comment]
The problem is TR9856 dataset certificate. Got it to work deleting line 370 from https://github.com/kudkudak/word-embeddings-benchmarks/blob/2b56c401ea4bba335ebfc0c8c5c4f8ba6394f2cd/web/evaluate.py#L370 and then installing again

**Comment by kudkudak** [comment]
Thanks so much for figuring this out. Could you please propose a PR?

**Comment by kudkudak** [comment]
Went ahead and removed it myself. Thanks for help again
